baseURL = "https://prabhatsharma.in/"
languageCode = "en-us"
title = "Prabhat Sharma | Cloud, Machine Learning, Kubernetes"
# theme = "silhouette-hugo"
theme = "prabhat-simple"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "Gallery"
        url     = "/gallery"
        weight  = 2
    [[menu.nav]]
        name    = "Kubernetes"
        url     = "/tags/kubernetes"
        weight  = 3
    [[menu.nav]]
        name    = "AWS"
        url     = "/tags/aws"
        weight  = 3
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 4

# Site Params
[params]
    home = "Home"
    logo = "images/logo4.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider3.jpg"
        heading = "Hello, I am \"Prabhat Sharma\". I am a"
        description = "Professionally, I work as a Solutions Architect and help people make best use of AWS"
        [[params.banner.flipText]]
            title   = "Builder"
        [[params.banner.flipText]]
            title   = "Father"
        [[params.banner.flipText]]
            title   = "Husband"
        [[params.banner.flipText]]
            title   = "Son"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "About Me"
        content = "I am a technologist who loves dabbling with interesting technologies that have the potential for improving the lives of technology teams and non-technologists alike. Over a period of 15 years years of my professional experience, I have helped multiple organizations design, deploy and run large and small scale systems. <br><br> I am based out of San Francisco Bay area and can be reached at hi{{dot}}prabhat{{at}}gmail.com. <br><br> Apart from many other things, I have strengths in the area of:<br> <ol><li>Large scale system design</li><li>Cloud computing - AWS</li><li>Machine Learning</li></ol> I write: <ol><li>Go</li><li>Python</li><li>Javascript (Node, Vue)</li></ol> I currently work for AWS (Articles on this site are not endorsed by AWS) as Senior Solutions Architect."
        image   = "images/about/me.jpg"

    